// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcok_UroCox5ZB0pyk0SbnXswCo8dSJE',
    appId: '1:685371262860:android:de51011ffb0c5263c2f8a9',
    messagingSenderId: '685371262860',
    projectId: 'culinary-compass-c8dcc',
    storageBucket: 'culinary-compass-c8dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5M6ItdN6TmUm4sAQmHcs45sBkDViRm_M',
    appId: '1:685371262860:ios:dbf09ec18f3d1b66c2f8a9',
    messagingSenderId: '685371262860',
    projectId: 'culinary-compass-c8dcc',
    storageBucket: 'culinary-compass-c8dcc.appspot.com',
    iosBundleId: 'com.example.culinaryCompass',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlqgXJZ6i6C8VXwYn_pJzmjNdUlcJISc',
    appId: '1:685371262860:web:49000cae587433ddc2f8a9',
    messagingSenderId: '685371262860',
    projectId: 'culinary-compass-c8dcc',
    authDomain: 'culinary-compass-c8dcc.firebaseapp.com',
    storageBucket: 'culinary-compass-c8dcc.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5M6ItdN6TmUm4sAQmHcs45sBkDViRm_M',
    appId: '1:685371262860:ios:dbf09ec18f3d1b66c2f8a9',
    messagingSenderId: '685371262860',
    projectId: 'culinary-compass-c8dcc',
    storageBucket: 'culinary-compass-c8dcc.appspot.com',
    iosBundleId: 'com.example.culinaryCompass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDlqgXJZ6i6C8VXwYn_pJzmjNdUlcJISc',
    appId: '1:685371262860:web:4e9148f6e0d9cc58c2f8a9',
    messagingSenderId: '685371262860',
    projectId: 'culinary-compass-c8dcc',
    authDomain: 'culinary-compass-c8dcc.firebaseapp.com',
    storageBucket: 'culinary-compass-c8dcc.appspot.com',
  );

}